# Generated by Django 3.2.9 on 2021-11-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome da configuração que corresponde')),
                ('descricao', models.CharField(max_length=256, verbose_name='Valor da configuração')),
            ],
            options={
                'db_table': 'config_geral',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ref', models.IntegerField(verbose_name='Id da empresa')),
                ('tipo', models.IntegerField(verbose_name='Id do tipo')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome da empresa')),
                ('nome_fantasia', models.CharField(blank=True, max_length=256, verbose_name='Nome fantasia da empresa')),
                ('superior', models.IntegerField(null=True, verbose_name='Id? do superior')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ da empresa')),
                ('observacoes', models.CharField(blank=True, max_length=256, verbose_name='Observações da empresa')),
                ('contato', models.CharField(blank=True, max_length=256, verbose_name='Nome do contato da empresa')),
                ('email', models.CharField(blank=True, max_length=256, verbose_name='Email do contato da empresa')),
                ('telefone2', models.CharField(blank=True, max_length=24, verbose_name='Segundo telefone para contato')),
                ('ramal2', models.CharField(blank=True, max_length=256, verbose_name='Segundo ramal')),
                ('telefone1', models.CharField(blank=True, max_length=24, verbose_name='Primeiro telefone para contato')),
                ('ramal1', models.CharField(blank=True, max_length=256, verbose_name='Primeiro ramal')),
                ('fax', models.CharField(blank=True, max_length=256, verbose_name='Fax da empresa')),
                ('cep', models.CharField(blank=True, max_length=25, verbose_name='CEP da empresa')),
                ('rua', models.CharField(blank=True, max_length=256, verbose_name='Rua da empresa')),
                ('numero', models.IntegerField(null=True, verbose_name='Numero da empresa')),
                ('complemento', models.CharField(blank=True, max_length=128, verbose_name='Complemento da empresa')),
                ('bairro', models.CharField(blank=True, max_length=256, verbose_name='Bairro da empresa')),
                ('cidade', models.CharField(blank=True, max_length=256, verbose_name='Cidade da empresa')),
                ('estado', models.CharField(blank=True, max_length=128, verbose_name='Rua da empresa')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ref', models.IntegerField(verbose_name='Id externo do equipamento')),
                ('tipo', models.IntegerField(verbose_name='Tipo do equipamento')),
                ('fabricante', models.CharField(blank=True, max_length=256, verbose_name='Fabricante do equipamento')),
                ('modelo', models.CharField(blank=True, max_length=256, verbose_name='Modelo do equipamento')),
                ('patrimonio', models.CharField(blank=True, max_length=256, verbose_name='Patrimonio do equipamento')),
                ('numero_serie', models.CharField(blank=True, max_length=14, verbose_name='Numero de serie do equipamento')),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arkmedsdb.empresa', verbose_name='Id da empresa')),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ref', models.IntegerField(verbose_name='Id externo do chamado')),
                ('numero', models.CharField(blank=True, default='', max_length=14, verbose_name='Numero do chamado')),
                ('prioridade', models.IntegerField(default=1, verbose_name='Nível de prioridade do chamado')),
                ('cor_prioridade', models.CharField(blank=True, default='#ffffff', max_length=14, verbose_name='Hex da cor da prioridade')),
                ('chamado_arquivado', models.BooleanField(default=False, verbose_name='Chamado arquivado ou não')),
                ('descricao', models.CharField(blank=True, default='', max_length=256, verbose_name='Descricao do chamado')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arkmedsdb.equipamento', verbose_name='Id do equipamento')),
            ],
            options={
                'db_table': 'chamado',
            },
        ),
    ]
